export const SCREEN_NAME = {
  HOME: 'HomeScreen',
  DRAWER: 'DRAWER',
  BOTTOM_TABS: 'BOTTOM_TABS',
  NOTIFICATION: 'NOTIFICATION',
  RECORD: 'RECORD',
  BOOK_APPOINTMENT: 'BOOK_APPOINTMENT',
  APPOINTMENT_SUMMARY: 'APPOINTMENT_SUMMARY',
  FIND_ORDER: 'FIND_ORDER',
  SETTING: 'SETTING',
  APPOINTMENT: 'APPOINTMENT',
  SEARCH: 'SEARCH'
};
